// Core type definitions for Memorai
// Three-tier storage philosophy:
//   Tier 1 = raw timeline (immutable, append-only)
//   Tier 2 = annotations (re-extractable derived layer)
//   Tier 3 = indexes (storage-adapter internal, rebuildable)
// See ARCHITECTURE.md §1.4 for the full design rationale.

// ─────────────────────────────────────────────────────────────
// Shared shapes
// ─────────────────────────────────────────────────────────────

export type MemoryLevel = "segment" | "atomic_action" | "episode";
export type Modality = "text" | "vision" | "audio" | "multimodal";

export interface MediaPayload {
  frames?: Array<ImageData | { data: Uint8ClampedArray; width: number; height: number } | string>; // string = reference URL / blob key
  audio?: AudioBuffer | string; // string = reference
  video?: string; // reference to video segment (URL, blob key, path)
}

// ─────────────────────────────────────────────────────────────
// Tier 1 — Raw timeline (immutable)
// ─────────────────────────────────────────────────────────────

export interface RawContent {
  /** Original event content shape, preserved verbatim. */
  content: EventContent;
  /** Flat text projection of `content`, for indexing. Optional for media-only events. */
  text?: string;
  /** Multimodal references (image / audio / video / file). */
  media?: MediaPayload;
}

// ─────────────────────────────────────────────────────────────
// Tier 2 — Annotations (re-extractable)
// ─────────────────────────────────────────────────────────────

/**
 * Triple-store entry: (subject, predicate, object). Used by knowledge-graph
 * pathways. Produced by extractors that opt in (e.g. LLMExtractor).
 */
export interface KnowledgeTriple {
  subject: string;
  predicate: string;
  object: string;
  /** Optional confidence in [0,1]. */
  confidence?: number;
}

/**
 * Tier 2 derived annotations. `tags`, `salienceScore`, and `modality` always
 * carry a default. Open-ended annotation kinds (sentiment, topics, custom
 * extractor outputs, …) go under the `extensions` bag.
 */
export interface MemoryAnnotations {
  /** Canonical fact form generated by an extractor. */
  summary?: string;
  /** Multiple paraphrased fact forms — improves recall coverage. */
  facts?: string[];
  /** Longer description / expansion. */
  description?: string;
  /** Tags / entities / topics (lowercase canonical form). */
  tags: string[];
  /** Importance score in [0,1]. */
  salienceScore: number;
  /** Modality flags inferred from the raw content. */
  modality: Modality[];
  /** Embedding computed over raw.text + annotations.summary + facts joined. */
  embedding?: number[];
  /** Knowledge-graph triples extracted from the event. */
  triples?: KnowledgeTriple[];
  /** Open extension surface for custom annotation kinds. */
  extensions?: Record<string, unknown>;
}

// ─────────────────────────────────────────────────────────────
// Cross-cutting metadata
// ─────────────────────────────────────────────────────────────

export interface MemoryMeta {
  /** AI agent that processed/wrote this memory (from agentProfile). */
  sourceAgent: string;
  /** Free-form agent role label. */
  agentRole: string;
  /** Free-form context attached at write time. */
  writeContext?: string;
  /** Additional event participants beyond actor/target (e.g., multi-party calls). */
  participants?: string[];
  /** Original Event.id, for back-reference and dedup. */
  eventId?: string;
  /** Wall-clock of last retrieve(). */
  lastAccessed?: number;
  /** Number of times this node has been retrieved. */
  accessCount: number;
  /** Unix ms when EventIdentifier ran on this node (undefined = not yet). */
  identifiedAt?: number;
}

// ─────────────────────────────────────────────────────────────
// MemoryNode — the persisted unit
// ─────────────────────────────────────────────────────────────

export interface MemoryNode {
  id: string;
  timestamp: number; // Unix ms — when this memory ends
  duration: number; // Duration in ms
  level: MemoryLevel;
  /** Data ownership / multi-tenant scope. */
  userId?: string;
  /** Who produced the original event (person / system). */
  actor?: string;
  /** Whom the event was directed at. */
  target?: string;
  parentId?: string;
  childrenIds?: string[];
  mergedFrom?: string[];
  /** Tier 1 — immutable raw record. Never modified by an extractor. */
  raw: RawContent;
  /** Tier 2 — derived annotations. Replaceable via Memorai.reAnnotate(). */
  annotations: MemoryAnnotations;
  /** Unix ms when `annotations` were last produced. */
  annotatedAt?: number;
  /** Free-form version string of the extractor that produced `annotations`. */
  annotationVersion?: string;
  meta: MemoryMeta;
}

/**
 * Back-compat alias. Earlier code referenced `MemoryPayload`; the closest
 * analogue in the new schema is the annotations layer. New code should
 * prefer `MemoryAnnotations` directly.
 */
export type MemoryPayload = MemoryAnnotations;

// ─────────────────────────────────────────────────────────────
// Write (internal API surface)
// ─────────────────────────────────────────────────────────────

/**
 * Loose annotation input — fields with natural defaults are optional.
 * Memorai.write() fills defaults to produce a fully-populated MemoryAnnotations.
 */
export interface MemoryAnnotationsInput {
  summary?: string;
  facts?: string[];
  description?: string;
  tags?: string[]; // default []
  salienceScore?: number; // default 0.5
  modality?: Modality[]; // default inferred from raw content
  embedding?: number[];
  triples?: KnowledgeTriple[];
  extensions?: Record<string, unknown>;
}

/**
 * Back-compat alias for code that used the old `MemoryPayloadInput`.
 */
export type MemoryPayloadInput = MemoryAnnotationsInput & { summary: string };

export interface WritePayload {
  timestamp?: number;
  duration?: number;
  /** Tier 1 — required. Extractors produce this verbatim from the Event. */
  raw: RawContent;
  /** Tier 2 — optional. Extractors that don't annotate omit this. */
  annotations?: MemoryAnnotationsInput;
  /** Version string of the extractor used; persisted on the node. */
  annotationVersion?: string;
  userId?: string;
  actor?: string;
  target?: string;
  parentId?: string;
  childrenIds?: string[];
  mergedFrom?: string[];
  meta?: Partial<MemoryMeta>;
}

export interface WriteOptions {
  skipEmbedding?: boolean; // if user already provided embedding
}

// ─────────────────────────────────────────────────────────────
// MemoryEvent — semantic event layer (Tier 2)
// ─────────────────────────────────────────────────────────────

/**
 * Three kinds of semantic events identified from raw MemoryNodes:
 *   - "state"      — an assertion that persists (e.g. "Alice likes apples"),
 *                    can be superseded by a newer state.
 *   - "transition" — a change from one state to another, with cause/trigger
 *                    (e.g. "Alice had an allergic reaction after eating nuts").
 *   - "happening"  — a discrete occurrence anchored in time (e.g. "Wed evening
 *                    emergency meeting Bob attended").
 */
export type MemoryEventKind = "state" | "transition" | "happening";

export interface MemoryEvent {
  id: string;
  kind: MemoryEventKind;
  /** Natural-language description — the canonical "what happened" sentence. */
  description: string;
  /** Entities involved (canonical names). */
  participants: string[];
  /** Tags / topics / categories. */
  topics: string[];
  /** When this event occurred (for happenings/transitions) or when this state
   *  was first observed to be true (for state events). Unix ms. */
  occurredAt: number;
  /** For state events: when this assertion was invalidated by a newer one.
   *  Undefined means "still believed true". */
  invalidatedAt?: number;
  /** IDs of MemoryEvents this one supersedes (typically when this is a state
   *  event that updates an older state). */
  supersedes?: string[];
  /** IDs of raw MemoryNodes this event was identified from. */
  sourceNodeIds: string[];
  /** Multi-tenant scope. Mirrors the originating raw node's userId. */
  userId?: string;
  /** Free-form actor label (who produced the underlying events). */
  actor?: string;
  /** Embedding over description + participants + topics. */
  embedding?: number[];
  /** Identifier's confidence in this extraction, [0, 1]. */
  confidence?: number;
  /** Free-form version string of the EventIdentifier that produced this. */
  identifierVersion?: string;
  meta: {
    /** When this event was first identified. */
    identifiedAt: number;
    /** Last time recall touched this event. */
    lastAccessed?: number;
    /** How many times recall has surfaced this event. */
    accessCount: number;
  };
}

export type MemoryEventOrderBy = "occurredAt" | "lastAccessed" | "confidence";

export interface EventQueryOpts {
  limit?: number;
  offset?: number;
  orderBy?: MemoryEventOrderBy;
  order?: Order;
  userId?: string;
  /** Filter by kind. */
  kind?: MemoryEventKind;
  /** Filter to events that are still believed valid at this point in time
   *  (invalidatedAt > validAt OR invalidatedAt undefined). */
  validAt?: number;
  /** Drop events with invalidatedAt set, regardless of validAt. Useful for
   *  "give me everything the agent currently believes" queries. */
  excludeInvalidated?: boolean;
}

/**
 * Event-level storage. Distinct from `StorageAdapter` (which stores raw
 * MemoryNodes) so that backends can pick their own physical layout. A default
 * in-memory implementation ships with the package and is wired automatically
 * when `MemoraiConfig.events` is omitted.
 */
export interface EventStore {
  putEvent: (event: MemoryEvent) => Promise<void>;
  getEvent: (id: string) => Promise<MemoryEvent | null>;
  deleteEvent: (id: string) => Promise<void>;
  batchPutEvents: (events: MemoryEvent[]) => Promise<void>;
  queryEventsByEmbedding: (
    embedding: number[],
    opts?: EventQueryOpts & { topK?: number },
  ) => Promise<MemoryEvent[]>;
  queryEventsByText: (
    text: string,
    opts?: EventQueryOpts & { topK?: number },
  ) => Promise<MemoryEvent[]>;
  queryEventsByParticipant: (participant: string, opts?: EventQueryOpts) => Promise<MemoryEvent[]>;
  queryEventsByTopic: (topic: string, opts?: EventQueryOpts) => Promise<MemoryEvent[]>;
  /** Events whose occurredAt falls in [start, end]. */
  queryEventsByTimeRange: (
    start: number,
    end: number,
    opts?: EventQueryOpts,
  ) => Promise<MemoryEvent[]>;
  listEvents: (opts?: EventQueryOpts) => Promise<MemoryEvent[]>;
  closeEventStore: () => Promise<void>;
}

// ─────────────────────────────────────────────────────────────
// Storage Adapter
// ─────────────────────────────────────────────────────────────

export type OrderBy = "timestamp" | "salience" | "lastAccessed";
export type Order = "asc" | "desc";

export interface QueryOpts {
  limit?: number;
  offset?: number;
  orderBy?: OrderBy;
  order?: Order;
  level?: MemoryLevel;
}

export interface StorageAdapter {
  put: (node: MemoryNode) => Promise<void>;
  get: (id: string) => Promise<MemoryNode | null>;
  delete: (id: string) => Promise<void>;
  batchPut: (nodes: MemoryNode[]) => Promise<void>;
  queryByTimeRange: (start: number, end: number, opts?: QueryOpts) => Promise<MemoryNode[]>;
  queryByTags: (tags: string[], opts?: QueryOpts) => Promise<MemoryNode[]>;
  queryBySalience: (minScore: number, opts?: QueryOpts) => Promise<MemoryNode[]>;
  queryByUserId: (userId: string, opts?: QueryOpts) => Promise<MemoryNode[]>;
  queryByActor: (actor: string, opts?: QueryOpts) => Promise<MemoryNode[]>;
  queryByTarget: (target: string, opts?: QueryOpts) => Promise<MemoryNode[]>;
  /**
   * Sparse keyword retrieval. Adapters implement this with BM25 (or an
   * equivalent best-effort) and return up to `limit` nodes ranked by
   * relevance. Returns [] if `text` produces no tokens.
   */
  queryByText: (text: string, opts?: QueryOpts & { limit?: number }) => Promise<MemoryNode[]>;
  getChildren: (parentId: string) => Promise<MemoryNode[]>;
  getParent: (childId: string) => Promise<MemoryNode | null>;
  listAll: (opts?: QueryOpts) => Promise<MemoryNode[]>;
  close: () => Promise<void>;
}

// ─────────────────────────────────────────────────────────────
// Embedding Service
// ─────────────────────────────────────────────────────────────

export interface EmbeddingService {
  embed: (text: string) => Promise<number[]>;
  embedBatch?: (texts: string[]) => Promise<number[][]>;
  dimension: number;
}

// ─────────────────────────────────────────────────────────────
// LLM Service (used by LLMExtractor + salience scoring)
// ─────────────────────────────────────────────────────────────

export interface LLMMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

export interface LLMCompletionOptions {
  temperature?: number;
  maxTokens?: number;
  responseFormat?: "text" | "json";
  signal?: AbortSignal;
}

export interface LLMService {
  /** Single-turn completion. Required. */
  complete: (prompt: string, opts?: LLMCompletionOptions) => Promise<string>;
  /** Multi-turn chat. Optional — falls back to `complete` joining messages. */
  chat?: (messages: LLMMessage[], opts?: LLMCompletionOptions) => Promise<string>;
}

// ─────────────────────────────────────────────────────────────
// Reranker Service (cross-encoder layer over fused candidates)
// ─────────────────────────────────────────────────────────────

export interface RerankDoc {
  id: string;
  text: string;
}

export interface RerankResult {
  id: string;
  score: number;
}

export interface RerankerService {
  /**
   * Rescore (query, doc) pairs and return the top-K by relevance.
   * The returned list is sorted descending by score; docs not in the
   * returned list are considered filtered out.
   */
  rerank: (query: string, docs: RerankDoc[], topK: number) => Promise<RerankResult[]>;
}

// ─────────────────────────────────────────────────────────────
// Evolution
// ─────────────────────────────────────────────────────────────

export interface AutoEvolveTriggers {
  /** Fire `evolve()` every N writes since the last evolve. Default 100. */
  onWriteCount?: number;
  /** Fire `evolve()` after N ms of write-idle. Default 5000. */
  onIdleMs?: number;
  /** Fire `evolve()` when stmMaxSize is reached. Default true. */
  onStmFull?: boolean;
  /** Fire one last `evolve()` from close(). Default true. */
  onClose?: boolean;
  /** Background interval (ms). Off by default — explicit opt-in. */
  intervalMs?: number;
}

export interface EvolutionConfig {
  semanticMergeThreshold: number; // default: 0.85
  temporalGapThresholdMs: number; // default: 30000
  sceneSimilarityThreshold: number; // default: 0.80
  episodeTimeWindowMs: number; // default: 300000
  stmMaxSize: number; // default: 1000
  /** "auto" runs triggers; "manual" requires explicit `evolve()` calls. */
  mode: "auto" | "manual";
  autoTriggers: AutoEvolveTriggers;
}

// ─────────────────────────────────────────────────────────────
// Retrieval (internal — wrapped by recall())
// ─────────────────────────────────────────────────────────────

export type RetrievalStrategy = "factual" | "temporal" | "inferential" | "exploratory";

export type TraversalOrder = "forward" | "reverse" | "salience";

export interface RetrievalQuery {
  text?: string;
  embedding?: number[];
  strategy: RetrievalStrategy;
  earlyStop?: boolean;
  timeRange?: { start: number; end: number };
  traversalOrder?: TraversalOrder;
  agentRole?: string;
  userId?: string;
  actor?: string;
  target?: string;
  level?: MemoryLevel;
  maxCandidates?: number;
  topK?: number;
}

export interface TraversalStats {
  scanned: number;
  matched: number;
  pruned: number;
  timeMs: number;
}

export interface RetrievalResult {
  nodes: MemoryNode[];
  confidence: number;
  traversalStats: TraversalStats;
}

// ─────────────────────────────────────────────────────────────
// Cross-Agent
// ─────────────────────────────────────────────────────────────

export interface WritePolicy {
  levels: MemoryLevel[];
  modalities: Modality[];
  salienceBoost: number;
}

export interface ReadPolicy {
  defaultLevel: MemoryLevel;
  defaultTraversal: TraversalOrder;
  timeHorizonMs: number;
}

export interface AgentMemoryProfile {
  agentId: string;
  /** Free-form role label — "reasoning" / "proactive" / app-specific. */
  role: string;
  writePolicy: WritePolicy;
  readPolicy: ReadPolicy;
}

// ─────────────────────────────────────────────────────────────
// Event API (public)
// ─────────────────────────────────────────────────────────────

export type EventContent =
  | { kind: "message"; text: string }
  | { kind: "speech"; text: string; audio?: AudioBuffer | string }
  | { kind: "image"; image: ImageData | string; caption?: string }
  | { kind: "audio"; audio: AudioBuffer | string; transcript?: string }
  | { kind: "video"; video: string; frames?: ImageData[]; transcript?: string }
  | { kind: "file"; mime: string; ref: string; text?: string }
  | { kind: "observation"; text: string }
  | { kind: "custom"; text: string; data?: Record<string, unknown> };

export interface Event {
  // —— time anchor (one required) ——
  at?: number | Date;
  during?: { start: number | Date; end: number | Date };

  // —— participants ——
  actor: string;
  target?: string;
  participants?: string[];

  // —— payload ——
  content: EventContent;

  // —— optional metadata ——
  userId?: string;
  context?: string;
  tags?: string[];
  salienceHint?: number;
  id?: string;
}

export interface RecordHandle {
  readonly eventIds: readonly string[];
  readonly nodes: Promise<MemoryNode[]>;
  done(): boolean;
  cancel(): void;
}

// ─────────────────────────────────────────────────────────────
// Extraction Pipeline
// ─────────────────────────────────────────────────────────────

export interface ExtractContext {
  /** Recent memories from the same actor/target window — for coreference. */
  recent: MemoryNode[];
  embedding: EmbeddingService;
  llm?: LLMService;
  now(): number;
  signal?: AbortSignal;
}

export interface Extractor {
  /** Convert a raw event into one or more memory writes. */
  extract: (event: Event, ctx: ExtractContext) => Promise<WritePayload[]>;
}

// ─────────────────────────────────────────────────────────────
// Event Identification — turns raw nodes into MemoryEvents
// ─────────────────────────────────────────────────────────────

/**
 * A new event the EventIdentifier wants to insert, optionally with a list of
 * pre-existing event IDs it supersedes. The Memorai pipeline assigns the
 * actual id + meta on persist.
 */
export interface IdentifiedEvent {
  kind: MemoryEventKind;
  description: string;
  participants: string[];
  topics: string[];
  occurredAt: number;
  sourceNodeIds: string[];
  /** When this is a state event that replaces older ones, the identifier
   *  populates this list so the pipeline can mark them invalidated. */
  supersedes?: string[];
  confidence?: number;
}

export interface IdentifyContext {
  /** Raw nodes that are candidates for identification (a recent batch). */
  nodes: MemoryNode[];
  /** Existing related MemoryEvents in scope — given to the LLM as context
   *  so it can decide INSERT vs SUPERSEDE on state assertions. */
  relatedEvents: MemoryEvent[];
  embedding: EmbeddingService;
  llm?: LLMService;
  now(): number;
  signal?: AbortSignal;
}

export interface EventIdentifier {
  /** Free-form version string persisted on every produced event. */
  readonly version: string;
  /** Identify semantic events from a batch of raw nodes. */
  identify: (ctx: IdentifyContext) => Promise<IdentifiedEvent[]>;
}

// ─────────────────────────────────────────────────────────────
// Recall API (public)
// ─────────────────────────────────────────────────────────────

export interface RecallOptions {
  topK?: number;
  timeRange?: { start: number; end: number };
  actor?: string;
  target?: string;
  userId?: string;
  modality?: Modality[];
  level?: MemoryLevel;
  strategy?: RetrievalStrategy;
  traversalOrder?: TraversalOrder;
  /** Generate N paraphrases of the question with the configured LLM and fuse their results. Requires MemoraiConfig.llm. */
  queryExpansion?: number;
  /** HyDE — generate a hypothetical answer with the LLM, embed it, use as an extra semantic pathway. Requires MemoraiConfig.llm. */
  hyde?: boolean;
  /** Disable event-level recall even if an EventIdentifier is configured.
   *  Defaults to true (event recall on) when an identifier is set. */
  includeEvents?: boolean;
  /** Drop events that have been superseded (invalidatedAt set) from the
   *  event-level pathway. Defaults to true — recall returns what the agent
   *  currently believes, not the full audit trail. */
  excludeInvalidatedEvents?: boolean;
  /** Power user escape hatch — overrides go straight to RetrievalQuery. */
  overrideQuery?: Partial<RetrievalQuery>;
}

export interface RecalledMemoryProvenance {
  /** Names of the retrieval pathways that surfaced this memory. */
  pathways: string[];
  /** RRF-fused score across all surfacing pathways. */
  fusedScore: number;
  /** Per-pathway raw score (semantic cosine, BM25 weight, etc.) for transparency. */
  pathwayScores?: Record<string, number>;
}

export interface RecalledMemory {
  id: string;
  at: number;
  during?: { start: number; end: number };
  userId?: string;
  actor?: string;
  target?: string;
  summary: string;
  description?: string;
  tags: string[];
  salienceScore: number;
  evidence?: MediaPayload;
  score: number;
  level: MemoryLevel;
  /**
   * Set when this hit was derived from the MemoryEvent layer (Tier 2.5)
   * rather than from a raw MemoryNode. The semantic-event surface returns
   * canonical state assertions / transitions / happenings whose schema is
   * different from raw nodes; callers can branch on `eventKind` to render
   * differently or filter event-derived hits in or out.
   */
  eventKind?: MemoryEventKind;
  /**
   * For event-derived hits, the raw MemoryNode IDs the event was
   * identified from. Used by recall fusion to dedupe redundant node-level
   * hits whose content already informed a surfaced event.
   */
  sourceNodeIds?: readonly string[];
  /** Multi-pathway retrieval evidence — which routes found this memory. */
  provenance?: RecalledMemoryProvenance;
}

export interface RecallResult {
  memories: RecalledMemory[];
  confidence: number;
  totalScanned: number;
}

// ─────────────────────────────────────────────────────────────
// Patch (used by Memorai.update)
// ─────────────────────────────────────────────────────────────

export interface NodePatch {
  /**
   * Partial annotation update — preferred path. The raw (Tier 1) record is
   * intentionally NOT patchable through this surface; use reAnnotate() to
   * regenerate annotations instead.
   */
  annotations?: Partial<MemoryAnnotations>;
  /** @deprecated alias for `annotations`. */
  payload?: Partial<MemoryAnnotations>;
  meta?: Partial<MemoryMeta>;
  userId?: string;
  actor?: string;
  target?: string;
  parentId?: string;
  childrenIds?: string[];
  mergedFrom?: string[];
}

// ─────────────────────────────────────────────────────────────
// Re-Annotation (Tier 2 regeneration from Tier 1)
// ─────────────────────────────────────────────────────────────

export interface ReAnnotateOptions {
  /** Use this extractor instead of the configured one. */
  extractor?: Extractor;
  /** Only re-annotate nodes that pass this filter. */
  filter?: (node: MemoryNode) => boolean;
  /** Skip recomputing embeddings (e.g. when the embedder is unchanged). */
  skipEmbedding?: boolean;
  /** Progress callback fired after each node. */
  onProgress?: (done: number, total: number) => void;
}

export interface ReAnnotateResult {
  /** Nodes whose Tier 2 annotations were regenerated. */
  reannotated: number;
  /** Nodes the extractor emitted no payload for (kept as-is). */
  skipped: number;
  /** Per-node failures, keyed by node id. */
  errors: Array<{ id: string; error: string }>;
}

// ─────────────────────────────────────────────────────────────
// Main Config
// ─────────────────────────────────────────────────────────────

export interface MemoraiConfig {
  storage: StorageAdapter;
  embedding: EmbeddingService;
  compression?: CompressionService;
  llm?: LLMService;
  extractor?: Extractor;
  /**
   * Event identification layer. Turns raw MemoryNodes into MemoryEvents
   * (state / transition / happening) during `evolve()`. When omitted along
   * with `events`, the event-identification path is disabled and recall
   * falls back to raw-node retrieval only.
   */
  identifier?: EventIdentifier;
  /**
   * Event-level storage. Defaults to an in-memory implementation when
   * omitted. Set when you want events to persist alongside raw nodes.
   */
  events?: EventStore;
  /**
   * Optional reranker — when set, recall() applies it as a final pass over
   * the fused top-N to improve precision. See LLMReranker for a built-in
   * that uses MemoraiConfig.llm.
   */
  reranker?: RerankerService;
  evolution?: Partial<EvolutionConfig>;
  agentProfile?: AgentMemoryProfile;
  /** Default actor when Event.actor is omitted. */
  defaultActor?: string;
  /** Default userId when Event.userId is omitted. */
  defaultUserId?: string;
  /** Logical namespace (multi-tenant separation). */
  namespace?: string;
}

export interface ListOptions extends QueryOpts {
  agentRole?: string;
}

// ─────────────────────────────────────────────────────────────
// Compression
// ─────────────────────────────────────────────────────────────

export interface VideoCompressConfig {
  maxWidth?: number;
  maxHeight?: number;
  fps?: number;
  quality?: number; // 0.0 - 1.0
  format?: "webp" | "jpeg" | "mp4";
}

export interface AudioCompressConfig {
  sampleRate?: number;
  channels?: number;
  bitrate?: number; // kbps
  format?: "mp3" | "ogg" | "wav";
}

export interface ImageCompressConfig {
  maxWidth?: number;
  maxHeight?: number;
  quality?: number; // 0.0 - 1.0
  format?: "webp" | "jpeg" | "png";
}

export interface CompressedVideo {
  ref: string; // URL / path / blob key
  width: number;
  height: number;
  durationMs: number;
  format: string;
  sizeBytes: number;
}

export interface CompressedAudio {
  ref: string;
  durationMs: number;
  sampleRate: number;
  format: string;
  sizeBytes: number;
}

export interface CompressedImage {
  ref: string;
  width: number;
  height: number;
  format: string;
  sizeBytes: number;
}

export interface CompressionService {
  compressVideo: (frames: ImageData[], config?: VideoCompressConfig) => Promise<CompressedVideo>;

  compressAudio: (buffer: AudioBuffer, config?: AudioCompressConfig) => Promise<CompressedAudio>;

  compressImage: (image: ImageData, config?: ImageCompressConfig) => Promise<CompressedImage>;
}
